/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Footer: React.FC = () => {
  return (
    <footer className="self-center mt-5">
      <span className="text-zinc-500">Já possui uma conta?</span>
      <span className="font-semibold"> Realize o login</span>
    </footer>
  );
};

export default Footer;
