/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Header: React.FC = () => {
  return (
    <header className="relative self-start text-xl font-semibold text-black max-md:max-w-full">
      SWAPTOOLS
    </header>
  );
};

export default Header;
