/**
 * This code was generated by Builder.io.
 */
import React from "react";
import InputField from "./InputField";

const RegistrationForm: React.FC = () => {
  return (
    <form className="flex relative flex-col grow px-9 pt-8 pb-3 w-full text-base font-light text-black bg-white rounded-xl border border-solid shadow-2xl border-zinc-500 max-md:px-5 max-md:mt-10 max-md:max-w-full">
      <h1 className="text-2xl max-md:max-w-full">Seja Bem Vindo!</h1>
      <h2 className="mt-5 text-3xl font-medium max-md:max-w-full">
        Catastre-se
      </h2>

      <InputField label="Email" placeholder="Enter your email" type="email" />
      <InputField
        label="Nome"
        placeholder="Entre com o seu email"
        type="text"
      />
      <InputField
        label="Senha"
        placeholder="Enter your Password"
        type="password"
        showToggle
      />
      <InputField
        label="Confirme a senha"
        placeholder="Confrim your Password"
        type="password"
        showToggle
      />

      <button className="justify-center items-center px-16 py-5 mt-7 font-medium text-white whitespace-nowrap bg-black rounded-md max-md:px-5 max-md:max-w-full">
        Register
      </button>

      <p className="self-center mt-5 font-medium text-zinc-400">
        ou continue com
      </p>

      <button className="flex gap-2 px-20 py-3 mt-4 mr-7 ml-8 text-xs rounded-2xl border border-violet-100 border-solid text-zinc-900 max-md:px-5 max-md:mx-2.5">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/d048ed030aae05ce9867f894c6f84a2f1cd9d5cebc756872fedd0827b4b28c28?apiKey=e659b181c3ec4be580186cc59fea34e1&"
          alt=""
          className="shrink-0 aspect-square w-[30px]"
        />
        <span className="flex-auto my-auto">
          Continuar com o G<strong>oogle</strong>
        </span>
      </button>
    </form>
  );
};

export default RegistrationForm;
