/**
 * This code was generated by Builder.io.
 */
import React from "react";

type InputFieldProps = {
  label: string;
  placeholder: string;
  type: string;
  showToggle?: boolean;
};

const InputField: React.FC<InputFieldProps> = ({
  label,
  placeholder,
  type,
  showToggle,
}) => {
  return (
    <div>
      <label
        htmlFor={`input-${label}`}
        className="mt-5 block max-md:max-w-full"
      >
        {label}
      </label>
      <div className="flex gap-5 px-7 py-5 mt-4 text-sm bg-white rounded-md border border-solid border-zinc-800 text-neutral-400 max-md:flex-wrap max-md:px-5 max-md:max-w-full">
        <input
          type={type}
          id={`input-${label}`}
          placeholder={placeholder}
          className="flex-auto"
        />
        {showToggle && (
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/ee37ca083ce79e088b4fa8823ecb39d072b3c4ece6c11e4b6a3ec0869c17bf5e?apiKey=e659b181c3ec4be580186cc59fea34e1&"
            alt=""
            className="shrink-0 aspect-square w-[21px]"
          />
        )}
      </div>
    </div>
  );
};

export default InputField;
