/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "../pages/auth/cadastro/Components/Header";
import Footer from "../pages/auth/cadastro/Components/Footer";

type LayoutProps = {
  children: React.ReactNode;
};

const Layout: React.FC<LayoutProps> = ({ children }) => {
  return (
    <div className="flex flex-col justify-center bg-white">
      <Header />
      <main className="flex overflow-hidden relative flex-col px-11 py-10 w-full blur-[3.9000000953674316px] min-h-[900px] max-md:px-5 max-md:max-w-full">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/4db85b513cb6fcd10691b5ec2669a832160b4c5f4c679d5141856fcf3b1b329f?apiKey=e659b181c3ec4be580186cc59fea34e1&"
          alt=""
          className="object-cover absolute inset-0 size-full"
        />
        {children}
      </main>
      <Footer />
    </div>
  );
};

export default Layout;
